# Generated by Django 6.0.3 on 2026-04-19 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classmodel',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='classstudent',
            options={'managed': True},
        ),
    ]
