# Generated by Django 5.2.12 on 2026-05-04 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=255)),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='designation.designation')),
            ],
            options={
                'db_table': 'staff',
                'managed': True,
            },
        ),
    ]
