# Generated by Django 4.1 on 2026-04-16 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_department_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'managed': True},
        ),
    ]
